In [4]:
#Create a NumPy array of integers from 1 to 10.
# Exercise 1
import numpy as np

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#Create a 3x3 NumPy array filled with zeros.
# Exercise 2

b = np.arange(1,10).reshape((3,3))
v = (0,0,0)
print(b*v)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [24]:
g = np.zeros(9).reshape(3,3)
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
#Create a NumPy array of 10 evenly spaced numbers between 0 and 5.
# Exercise 3

c = np.linspace(0,5,10, endpoint= False)
print(c)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [29]:
#Create a 5x5 identity matrix using NumPy.
# Exercise 4

d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
#Create a 4x4 matrix with random values between 0 and 1.
# Exercise 5

e = np.random.rand(4,4)
e

array([[0.79893564, 0.65071415, 0.99017769, 0.10460525],
       [0.94453314, 0.65782262, 0.3309628 , 0.6193133 ],
       [0.00468567, 0.19135893, 0.52648858, 0.81489059],
       [0.66994833, 0.07812234, 0.38615024, 0.21814247]])

In [33]:
#Exercise 6:
#Find the shape of a NumPy array.
# Exercise 6

print(e.shape)

(4, 4)


In [34]:
np.random.seed(10)

In [35]:
e = np.random.rand(4,4)
e

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [36]:
np.random.seed(0)

In [37]:
e = np.random.rand(4,4)
e

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [38]:
#Exercise 7:
#Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.
# Exercise 7

A = np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
A.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
#Exercise 8:
#Find the data type of the elements in a NumPy array.
# Exercise 8

A.dtype

dtype('int64')

In [45]:
#Exercise 9:
#Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.
# Exercise 9

A = np.arange(0,101,2)
A

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [48]:
#Exercise 10:
#Generate a 6x6 matrix of random integers between 10 and 50.
# Exercise 10

A = np.random.randint(10,50,(6,6))
A

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])

In [70]:
#Slice a 2D NumPy array to extract a submatrix.
# Exercise 11

p = np.random.randint(10, size=(3, 4))
print(p)
submatrix = p[0:2, 0:2]
submatrix

[[3 6 9 8]
 [0 8 5 9]
 [0 9 6 5]]


array([[3, 6],
       [0, 8]])

In [57]:
#Calculate the sum of all elements in a NumPy array.
# Exercise 12

f = np.arange(10)
print(f)
print(np.sum(f))

[0 1 2 3 4 5 6 7 8 9]
45


In [60]:
#Calculate the mean, median, and standard deviation of a NumPy array.
# Exercise 13

print(np.mean(f))

4.5


In [62]:
print(np.median(f))

4.5


In [66]:
print(np.std(f))

2.8722813232690143


In [67]:
#Find the maximum and minimum values in a NumPy array.
# Exercise 14

print(np.max(f))

9


In [68]:
print(np.min(f))

0


In [91]:
#Create a NumPy array of 20 random integers and find the index of the maximum value.
# Exercise 15

h = np.random.randint(1,21,(5,5))
print(h)
print(np.argmax(h))

[[17  4 11  2  5]
 [ 5 17 17 16 11]
 [14  9 12  7 10]
 [16  4 20 13 19]
 [18 11  3  2 12]]
17


In [92]:
#Create a NumPy array and reverse its elements.
# Exercise 16

print(np.flip(h))

[[12  2  3 11 18]
 [19 13 20  4 16]
 [10  7 12  9 14]
 [11 16 17 17  5]
 [ 5  2 11  4 17]]


In [5]:
#Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.
# Exercise 17

k = np.arange(9).reshape(3,3)
print(k)
print("\n")
i = np.arange(9).reshape(3,3)
print(i)
print("\n")
print(k*i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [101]:
#Create a diagonal matrix from a given 1D array.
# Exercise 18

l = np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [9]:
#Perform matrix multiplication on two 2D NumPy arrays.
# Exercise 19

w = np.arange(12).reshape(3,4)
print(w)
print("\n")
q = np.arange(12).reshape(3,4)
print(q)
print("\n")
print(w*q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [106]:
#Flatten a 2D NumPy array into a 1D array.
# Exercise 20

print(k.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
#Stack two NumPy arrays vertically.
# Exercise 21

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


result_vstack = np.vstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\n")
print(result_vstack)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
#Stack two NumPy arrays horizontally.
# Exercise 22

result_hstack = np.hstack((array1, array2))
print(result_hstack)

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
#Split a NumPy array into multiple sub-arrays.
# Exercise 23

array = np.arange(9)  
print(np.array_split(array, 3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [20]:
#Generate a random NumPy array and round each element to two decimal places.
# Exercise 24

array = np.round(np.random.rand(5, 5), 2)
print(array)

[[0.66 0.79 0.31 0.32 0.75]
 [0.56 0.51 0.25 0.27 0.46]
 [0.11 0.37 0.85 0.26 0.13]
 [0.53 0.47 0.82 0.68 0.52]
 [0.39 0.33 0.46 0.99 0.61]]


In [21]:
#Find the unique elements of a NumPy array.
# Exercise 25

y = np.array([1, 2, 2, 3, 4, 4, 5]) 
print(np.unique(y))

[1 2 3 4 5]


In [24]:
#Replace all elements in a NumPy array that are less than a specific value with that value.
# Exercise 26

y[ y < 4 ] = 5
print(y)

[5 5 5 5 4 4 5]


In [25]:
#Find the cumulative sum of the elements in a NumPy array.
# Exercise 27

print(np.cumsum(y))

[ 5 10 15 20 24 28 33]


In [26]:
#Create a NumPy array and find the number of non-zero elements in it.
# Exercise 28

z = np.array([0, 1, 2, 0, 3, 4, 0])
print(np.count_nonzero(z))

4


In [33]:
#Create a NumPy array of random integers and sort it in ascending order.
# Exercise 29

r = np.random.randint(1,9, size = 7)
print(r)
print("\n")
print(np.sort(r))


[2 5 5 5 8 4 6]


[2 4 5 5 5 6 8]


In [41]:
#Find the row-wise and column-wise sum of a 3x3 matrix.
# Exercise 30

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_wise_sum = np.sum(matrix, axis=1)

column_wise_sum = np.sum(matrix, axis=0)

print("Row-wise sum:", row_wise_sum)
print("Column-wise sum:", column_wise_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


In [35]:
#Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).
# Exercise 31


# Generate a 2D NumPy array with random values (for example, a 3x3 matrix)
x = np.random.rand(3, 3)

matrix_min = x.min()
matrix_max = x.max()

normalized_matrix = (matrix - matrix_min) / (matrix_max - matrix_min)

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Matrix:
 [[ 1.22663978  2.53181035  3.83698092]
 [ 5.14215148  6.44732205  7.75249261]
 [ 9.05766318 10.36283374 11.66800431]]


In [40]:
#Create two NumPy arrays and find the dot product.
# Exercise 32

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(np.dot(a1, a2))


32


In [42]:
#Find the trace of a square NumPy matrix.
# Exercise 33

print(np.trace(matrix))


15


In [46]:
#Create a 2D array and swap two rows.
# Exercise 34

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(array)
array[[0, 2]] = array[[2, 0]]
print("\n")
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [44]:
#Create a 1D NumPy array and convert it into a column vector.
# Exercise 35

array = np.array([1, 2, 3, 4, 5])

column_vector = array.reshape(-1, 1)
print(column_vector)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [51]:
#Find the determinant of a 3x3 matrix.
# Exercise 36

array5 = np.array([[2, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(array)
print(np.linalg.det(array5))

[1 2 3 4 5]
-3.0000000000000018


In [53]:
#Find the eigenvalues and eigenvectors of a 2x2 matrix.
# Exercise 37

print(np.linalg.eig(array5))

(array([16.23499933,  0.32813711, -0.56313644]), array([[-0.24549726, -0.71374819, -0.5504281 ],
       [-0.52322258,  0.69718768, -0.39659509],
       [-0.81606938, -0.06702875,  0.73467084]]))


In [56]:
#Create a 4x4 matrix and extract the diagonal elements.
# Exercise 40

o = np.arange(16).reshape(4,4)
print(o)
print("\n")
print(np.diag(o))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[ 0  5 10 15]
